export const TxTag = {
  closePrismEtf: "closePrismEtf",
  closePrismEtfAta: "closePrismEtfAta",
  createPrismEtfPushTokens: "createPrismEtfPushTokens",
  createPrismEtfFinalized: "createPrismEtfFinalized",
  deletePrismEtf: "deletePrismEtf",
  listPrismEtf: "listPrismEtf",
  orderPrismEtfTransfer: "orderPrismEtfTransfer",
  orderPrismEtfFinalized: "orderPrismEtfFinalized",
  sourceInAsset: "sourceInAsset",
  sourceInAssetFinalized: "sourceInAssetFinalized",
  sourceOutAsset: "sourceOutAsset",
  sourceOutAssetFinalized: "sourceOutAssetFinalized",
  unlistPrismEtf: "unlistPrismEtf",
};
